---
title: "receptor pair graph"
output: html_notebook
---

```{r}
library(igraph)

g1 <- graph_from_edgelist(as.matrix(head(kegg.df.ordered.unique[,c(2,6)],100)),directed = T)
plot(g1, edge.arrow.size=.2, edge.curved=0, vertex.label.cex=.7, vertex.size=7)

# add pairs that are already in graph:
g2 <- graph_from_edgelist(as.matrix(
  unique(rbind(kegg.df.ordered.unique[kegg.df.ordered.unique$Enzyme1 %in% names(V(g1)),c(2,6)],
  kegg.df.ordered.unique[kegg.df.ordered.unique$Enzyme2 %in% names(V(g1)),c(2,6)]))))
V(g2)$color <- colrs[as.integer(names(V(g2)) %in% c("pld4","hk3","hpgds","gpx8"))+1]
plot(g2, edge.arrow.size=.1, edge.curved=0, vertex.label.cex=.1, vertex.size=3)
plot(decompose.graph(g2)[[1]], edge.arrow.size=.2, edge.curved=0, vertex.label.cex=.7, vertex.size=7)



# grow biggest subgraph
# grow biggest subgraph
g2 <- graph_from_edgelist(as.matrix(
  unique(rbind(kegg.df.ordered.unique[kegg.df.ordered.unique$Enzyme1 %in% names(V(decompose.graph(g1)[[2]])),c(2,6)],
  kegg.df.ordered.unique[kegg.df.ordered.unique$Enzyme2 %in% names(V(decompose.graph(g1)[[2]])),c(2,6)]))))
V(g2)$color <- colrs[as.integer(names(V(g2)) %in% c("pld4","hk3","hpgds","gpx8"))+1]
plot(g2, edge.arrow.size=.1, edge.curved=0, vertex.label.cex=.1, vertex.size=3)
plot(decompose.graph(g2)[[1]], edge.arrow.size=.2, edge.curved=0, vertex.label.cex=.7, vertex.size=7)

g3 <- graph_from_edgelist(as.matrix(
  unique(rbind(kegg.df.ordered.unique[kegg.df.ordered.unique$Enzyme1 %in% names(V(decompose.graph(g2)[[1]])),c(2,6)],
  kegg.df.ordered.unique[kegg.df.ordered.unique$Enzyme2 %in% names(V(decompose.graph(g2)[[1]])),c(2,6)]))))
V(g3)$color <- colrs[as.integer(names(V(g3)) %in% c("pld4","hk3","hpgds","gpx8"))+1]
plot(g3, edge.arrow.size=.1, edge.curved=0, vertex.label.cex=.1, vertex.size=3)

g4 <- graph_from_edgelist(as.matrix(
  unique(rbind(kegg.df.ordered.unique[kegg.df.ordered.unique$Enzyme1 %in% names(V(decompose.graph(g3)[[1]])),c(2,6)],
  kegg.df.ordered.unique[kegg.df.ordered.unique$Enzyme2 %in% names(V(decompose.graph(g3)[[1]])),c(2,6)]))))
V(g4)$color <- colrs[as.integer(names(V(g4)) %in% c("pld4","hk3","hpgds","gpx8"))+1]
plot(g4, edge.arrow.size=.1, edge.curved=0, vertex.label.cex=.1, vertex.size=3)


gr <- graph_from_edgelist(as.matrix(
  unique(rbind(kegg.df.ordered.unique[kegg.df.ordered.unique$Enzyme1 %in% c("hpgds"),c(2,6)],
  kegg.df.ordered.unique[kegg.df.ordered.unique$Enzyme2 %in% c("hpgds"),c(2,6)]))))
gr <- graph_from_edgelist(as.matrix(
  unique(rbind(kegg.df.ordered.unique[kegg.df.ordered.unique$Enzyme1 %in% names(V(decompose.graph(gr)[[1]])),c(2,6)],
  kegg.df.ordered.unique[kegg.df.ordered.unique$Enzyme2 %in% names(V(decompose.graph(gr)[[1]])),c(2,6)]))))
V(gr)$color <- colrs[as.integer(names(V(gr)) %in% c("pld4","hk3","hpgds","gpx8"))+1]
plot(gr, edge.arrow.size=.2, edge.curved=0, vertex.label.cex=.3, vertex.size=5)

hs <- hub_score(gr, weights=NA)$vector
as <- authority_score(gr, weights=NA)$vector

ceb <- cluster_edge_betweenness(gr) #clusters 5,64,
dendPlot(ceb, mode="hclust")
plot(ceb, gr) 

clp <- cluster_label_prop(gr)
plot(clp, gr, edge.arrow.size=.2, edge.curved=0, vertex.label.cex=.3, vertex.size=5)

cfg <- cluster_fast_greedy(as.undirected(gr))
plot(cfg, as.undirected(gr),edge.arrow.size=.2, edge.curved=0, vertex.label.cex=.3, vertex.size=5)
table(cfg$membership)
names(V(gr))[cfg$membership==3]

deg <- degree(gr, mode="all")
cut.off <- mean(links$weight) 
net.sp <- delete_edges(net, E(net)[weight<cut.off])

plot(net.sp) 

cell_type <-data.xu[match(names(V(g4)),tolower(data.xu$external_gene_name)),c(1,3,4)]
cell_type$max <- as.integer(cell_type$WT_MEF > cell_type$WT_BMDM) + 1
colrs <- c("gold", "tomato")
cell_type$color <- colrs[cell_type$max]
V(g3)$color <- cell_type$color

plot(g1, edge.arrow.size=.2, edge.curved=0, vertex.label.cex=.7, vertex.size=7)
legend(x=-1.5, y=-1.1, c("> in BMDM","> in MEF"), pch=21,
       col="#777777", pt.bg=colrs, pt.cex=2, cex=.8, bty="n", ncol=1)

```

```{r}

```

