---
title: "Untitled"
author: "DLL"
date: "5/19/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(data.table)
library(ggplot2)
library(reshape2)
```

```{r}
data.xu <- fread("~/Downloads/GSE104511_MEF_BMDM_expression.csv.gz", data.table=FALSE)
data.xu$cell_max <- as.integer(data.xu$WT_MEF < data.xu$WT_BMDM) + 1

data.xu.melted <- melt(data.xu[,c(1,3,4)])
colnames(data.xu.melted)[2] <- "cell_type"

ggplot(data.xu.melted,aes(log(value), color=cell_type, fill=cell_type)) + geom_histogram(position="identity", alpha=0.5)
```


```{r}
hist(log(data.xu$WT_MEF)-log(data.xu$WT_BMDM))

```
```{r}
#data.xu$logdiff <- log(log(data.xu$WT_MEF)/log(data.xu$WT_BMDM))
#data.xu$logdiff <- log(data.xu$WT_MEF) - log(data.xu$WT_BMDM)
data.xu$logdiff <- log(abs(data.xu$WT_MEF - data.xu$WT_BMDM))
data.xu$diff <- data.xu$WT_MEF - data.xu$WT_BMDM

data.xu.pruned <- data.xu[!is.infinite(data.xu$logdiff),]

data.xu.sorted <- data.xu.pruned[order(-data.xu.pruned$logdiff),]
data.xu.sorted <- data.xu.pruned[order(-abs(data.xu.pruned$diff)),]


head(data.xu.sorted,30)
```


```{r}
df <- melt(data.xu.sorted[c(1:30),c(1,3,4)])
ggplot(df,aes(external_gene_name, value, color=variable)) + geom_line() +
  geom_area(aes(fill = variable, group = variable), alpha = 0.5, position = 'identity') +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  ggtitle("top 30 genes with differential expression")
```


```{r}
head(data.xu.sorted2[,1],30)
```

```{r}
## metabolic pathway analysis

library(pathview)
library(org.Mm.eg.db)

data("demo.paths")
data("paths.hsa")

data.xu.pv <- (data.xu[,5])
colnames(data.xu.pv) <- data.xu.sorted$external_gene_name
names.xu.eg <- id2eg(data.xu$external_gene_name,org = "Mm",pkg.name = "org.Mm.eg.db")
names.xu.path <- eg2id(names.xu.eg[,2], category="path",org = "mmu", pkg.name = "org.Mm.eg.db")
colnames(data.xu.pv) <- names.xu.path[,2]

#names.xu.kegg = mget(names.xu.eg[,2], org.Mm.egPATH,ifnotfound=NA)

pv.out <- pathview(gene.data = data.xu.pv, pathway.id = "04978", species = "mmu", out.suffix = "xu", kegg.native = T)
```

```{r}
select(org.Mm.eg.db,keys=data.xu$MGI, columns=c("MGI","ENTREZID"),keytype = "MGI")
select(org.Mm.eg.db,keys=data.xu$MGI, columns=c("ENTREZID","MGI"))

library(stringi)
#data.xu$MGI <- apply(data.xu,1,function(x) stri_sub(x[2],-7,-2))
#data.xu$MGI <- apply(data.xu,1,function(x) as.numeric(gsub(".*?([0-9]+).*", "\\1", x[2])))
#data.xu$MGI <- apply(data.xu,1,function(x) as.numeric(gsub(".*?([0-9]+)+]+$", "\\1", x[2])))
data.xu$MGI <- apply(data.xu,1,function(x) gsub(".*:(.+)].*", "\\1", x[2]))
#data.xu$MGI <- apply(data.xu,1,function(x) as.numeric(gsub("\d+(?![^\r\n\d]*\d)", "\\1", x[2])))

#For the reverse map MGI2EG:
# Convert to a list
xx <- as.list(org.Mm.egMGI2EG)
if(length(xx) > 0){
   # Gets the entrez gene IDs for the first five MGI IDs
   xx[1:5]
   # Get the first one
   xx[[1]]
}
```

```{r}
## using mouse receptor-ligand list from https://github.com/LewisLabUCSD/Ligand-Receptor-Pairs/blob/master/Mouse/Mouse-2020-Shao-LR-pairs.txt

#load list
lrpair.list <- fread("~/Documents/Mouse-2020-Shao-LR-pairs.txt",data.table =FALSE)

length(intersect(names(table(lrpair.list$ligand_gene_symbol)),names(table(data.xu$external_gene_name)))) #646/651
setdiff(names(table(lrpair.list$ligand_gene_symbol)),names(table(data.xu$external_gene_name))) #"Ccl21d","Ccn1","Ccn2","Ccn3","Ntn3"  
length(intersect(names(table(lrpair.list$receptor_gene_symbol)),names(table(data.xu$external_gene_name)))) #586/588
setdiff(names(table(lrpair.list$receptor_gene_symbol)),names(table(data.xu$external_gene_name))) #"Cd244a" "Hjv" 

#mappings for the indirect mappings
library(plyr)

lrpair.list[,2] <- mapvalues(lrpair.list[,2], from=c("Cd244a","Hjv", "Ccn1", "Ccn2", "Ccn3") ,to=c("Cd244", "Hfe2", "Cyr61", "Ctcf", "Nov"))
lrpair.list[,3] <- mapvalues(lrpair.list[,3], from=c("Cd244a","Hjv", "Ccn1", "Ccn2", "Ccn3") ,to=c("Cd244", "Hfe2", "Cyr61", "Ctcf", "Nov"))

#redo and check for improvement
length(intersect(names(table(lrpair.list$ligand_gene_symbol)),names(table(data.xu$external_gene_name)))) #649/651
length(intersect(names(table(lrpair.list$receptor_gene_symbol)),names(table(data.xu$external_gene_name)))) #588/588

#make lrpair and values dataframe
lrpair.ligand <- merge(lrpair.list[,c(1,2)],data.xu[,c(1,3,4)],by.x="ligand_gene_symbol",by.y="external_gene_name")
lrpair.receptor <- merge(lrpair.list[,c(1,3)],data.xu[,c(1,3,4)],by.x="receptor_gene_symbol",by.y="external_gene_name")
lrpair.df <- merge(lrpair.ligand,lrpair.receptor,by="lr_pair")

#calculate significant lrpair scores
lrpair.ligand$log2diff <- log2(lrpair.ligand$WT_MEF+1)-log2(lrpair.ligand$WT_BMDM+1)
lrpair.receptor$log2diff <- log2(lrpair.receptor$WT_MEF+1)-log2(lrpair.receptor$WT_BMDM+1)
lrpair.df <- merge(lrpair.ligand,lrpair.receptor,by="lr_pair")

#get sig differentially expressed receptor-ligand pairs of opposite expression
head(lrpair.df[order(-abs(lrpair.df$log2diff.x-lrpair.df$log2diff.y)),],30)
lrpair.df.ordered <- lrpair.df[order(-abs(lrpair.df$log2diff.x-lrpair.df$log2diff.y)),]

fwrite(lrpair.df.ordered,file="~/Documents/Xu2018MEFBMDM_LRpairs.csv")

##retrospectively adding score
lrpair.df.ordered <- fread(file="~/Documents/Xu2018MEFBMDM_LRpairs.csv", data.table = FALSE)
lrpair.df.ordered$m1 <- abs(lrpair.df.ordered$log2diff.x-lrpair.df.ordered$log2diff.y)
```

